config/routes.rb
SampleApp::Application.routes.draw do

  get "users/new"

  root :to => 'static_pages#home'

  match '/about', :to => 'static_pages#about'

  match '/help', :to => 'static_pages#help'

  match '/home', :to => 'static_pages#home'

  match '/signup', :to => 'users#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def help
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Captainsmiley "
    if page_title.empty?
      base_title + "server"
    else
      custom_title = "#{base_title}" + "| #{page_title}"
        custom_title
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/help.html.erb
<h1>Home#help</h1>
<p>Find me in app/views/home/help.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to "sample app", '#', id: "logo" %>
        <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    home_path %></li>
          <li><%= link_to "Help",    help_path %></li>
          <li><%= link_to "Sign in", '#' %></li>
        </ul>
        </nav>
      </div>
    </div>
    </header>
    <div class="container">

      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>About page</h1>
    <p>
    blh blah

    </p>

app/views/static_pages/help.html.erb
<h1>Help page</h1>
<p>Här är en sida med hjälp</p>


<p> tgtest </p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center hero-unit">
  <h1>Welcome to Captainsmiley server</h1>

  <h2>
    This is a site for test
  </h2>

  <p>Version sample_app med rails 3.2 <br>
  <a href="http://railstutorial.org">Ruby on Rails Tutorial</a>


  </p>

  <%= link_to "Sign up now!", signup_path, :class => "btn btn-lage btn-primary" %>

</div>

<%= link_to image_tag("rails.png", :alt => "Rails"), 'http://rubyonrails.org/' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>Find meSign up in app/views/users/new.html.erb</p>